### Numpy处理多维数据，矩阵运算

In [2]:
import numpy as np     # load numpy module

In [5]:
a = np.array([1,2,3])   # 初始化一维数组
print(a)
print(a.shape)

[1 2 3]
(3,)


### 多维数组

In [24]:
m = np.array([[1,0,0,2],[2,3,1,2],[4,2,1,5]])
print(m)
print(m.shape)
print(m.ndim)  # dimension, 2-d array
print(m.size)   # # of elements
print(m.dtype)  # data type
print(m.reshape(2,3,2))  # reshape it to 3-d array
print(m.reshape(2,3,2).ndim)

[[1 0 0 2]
 [2 3 1 2]
 [4 2 1 5]]
(3, 4)
2
12
int64
[[[1 0]
  [0 2]
  [2 3]]

 [[1 2]
  [4 2]
  [1 5]]]
3


### 创建数组 

In [28]:
x = np.empty([3,2],dtype=int)   # create a 3x2 matrix
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [32]:
x = np.zeros(shape=[2,2],dtype=float)
print(x)

[[0. 0.]
 [0. 0.]]


In [44]:
x = np.ones((3,1))   # shape is not required
print(x)

[[1.]
 [1.]
 [1.]]


In [40]:
x = np.random.random((2,2))
print(x)

[[0.88860313 0.83883785]
 [0.20062435 0.8969351 ]]


In [46]:
x = np.eye(2)
print(x)

[[1. 0.]
 [0. 1.]]


### 转化已有数据为数组 

In [49]:
x = [[1,2,3,4],[2,2,5,5]]
a = np.asarray(x)
print(a)

[[1 2 3 4]
 [2 2 5 5]]


### 从数值范围创建

In [53]:
x = np.arange(start=0,stop=20,step=2,dtype=int)   # stop is not included
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [58]:
x = np.linspace(start=0, stop=5, num=50, endpoint=True, retstep=False, dtype= int)
print(x)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3 4 4 4 4 4 4 4 4 4 5]


In [60]:
x = np.logspace(1,2,num=10,base=2)
print(x)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]


### slicing and index 

In [63]:
x = np.arange(10)
print(x)
print(x[1:10:3])   # 1 to 10, step=3

[0 1 2 3 4 5 6 7 8 9]
[1 4 7]


In [78]:
x = np.random.random((3,2))
print(x)
print('\n')
print(x[2:])
print('\n')
print(x[2,1])

[[0.5878822  0.8264878 ]
 [0.89807475 0.91308714]
 [0.22107826 0.49665853]]


[[0.22107826 0.49665853]]


0.49665853437206087


高级索引

In [85]:
print(x[x>0.5])

[0.5878822  0.8264878  0.89807475 0.91308714]


### Broadcast (广播) 

当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制

In [86]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


### 迭代数组

In [96]:
x = np.random.random((4,3))
print(x)

[[0.37560937 0.13281395 0.29326529]
 [0.73843352 0.44487223 0.14748018]
 [0.68797843 0.20043966 0.29510874]
 [0.46313781 0.28141051 0.46551497]]


In [98]:
for i in np.nditer(x,order="C"):
    print(i, end=",")

0.37560937485597057,0.13281395214775715,0.2932652940064535,0.7384335198407649,0.44487222861052234,0.14748018176803246,0.6879784261837053,0.2004396612828655,0.2951087418967113,0.46313780967620943,0.281410512813411,0.46551496847479124,

### 修改数组 

In [100]:
x = np.arange(6).reshape(3,2)
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [107]:
print(x.flatten(order="F")) # by column

[0 2 4 1 3 5]


In [108]:
print(x.T)

[[0 2 4]
 [1 3 5]]


In [118]:
print(np.append(x,[[7,7]],axis=0))   # 注意两个中括号

[[0 1]
 [2 3]
 [4 5]
 [7 7]]


### 字符串运算 

In [131]:
print(np.char.add("Hello ","Python"))
print(np.char.multiply("No ",3))
print (np.char.center('Center', 20,fillchar = '*'))
print (np.char.title('i like python')) # Capitalize first letter
print (np.char.join(['~','-'],['China','USA']))

Hello Python
No No No 
*******Center*******
I Like Python
['C~h~i~n~a' 'U-S-A']


### 数学函数 

In [137]:
print(np.sin(np.pi))  # trigonometric functions
print(np.around(np.pi,7))
print(np.floor(1.2))

1.2246467991473532e-16
3.1415927
1.0


### 统计函数

In [144]:
x = np.random.random((4,3))
print(x)

[[0.76624286 0.94227223 0.32307902]
 [0.00502406 0.92261178 0.79708685]
 [0.27348432 0.91665084 0.66096186]
 [0.6161871  0.79470488 0.15561396]]


In [146]:
print(np.amin(x))
print(np.amin(x,1))   # min by row
print(np.amin(x,0))   # min by col

0.0050240611892193865
[0.32307902 0.00502406 0.27348432 0.15561396]
[0.00502406 0.79470488 0.15561396]


In [149]:
print(np.ptp(x))  # range between min and max
print(np.percentile(x,60))  # 60th percentile

0.9372481647904671
0.7833200733023536


In [154]:
a = np.linspace(0,10,9)
print(a)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [162]:
print(np.median(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))

5.0
5.0
3.227486121839514
10.416666666666666


In [160]:
wt = np.arange(9)
print(np.average(a,weights=wt))  # weighted-average

7.083333333333333


###  线性代数

矩阵相乘

In [8]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[3,1],[2,5]])
print("\n",b)

[[1 2]
 [3 4]]

 [[3 1]
 [2 5]]


In [9]:
print(np.dot(a,b))   # a times b

[[ 7 11]
 [17 23]]


In [11]:
print(a*b)    # elementwise multiplication

[[ 3  2]
 [ 6 20]]


In [13]:
print(np.vdot(a,b))  # vectorize each matrix and then calculte inner product

31


Matrix Inverse

In [16]:
a1 = np.mat(np.random.randn(2,2))
print(a1)

[[ 0.58822162  0.17369007]
 [ 0.40998023 -1.3138523 ]]


In [18]:
a2 = a1.I
print(a2)

[[ 1.55661252  0.20578275]
 [ 0.48573219 -0.69690721]]


In [20]:
print(np.dot(a1,a2))

[[1. 0.]
 [0. 1.]]


Find min, max, sum

In [37]:
a = np.array([[3,2,1],[4,5,6],[7,9,8]])
print(a)

[[3 2 1]
 [4 5 6]
 [7 9 8]]


In [26]:
print(a.sum(axis=0))  # col sum
print(a.sum(axis=1)) # row sum

[14 16 15]
[ 6 15 24]


In [36]:
print(np.max(a[:,2]))  # the max of third col
print(np.max(a,1))  # max of each row
print(np.argmax(a,0)) # index of max at each col

8
[3 6 9]
[2 2 2]


矩阵的分割和合并

In [47]:
a = np.ones((2,2))
print(a)

b = np.eye(2)
print("\n")
print(b)

[[1. 1.]
 [1. 1.]]


[[1. 0.]
 [0. 1.]]


In [50]:
np.vstack((a,b))   # concatenate by row 

array([[1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.]])

In [51]:
np.hstack((a,b))   # concatenate by col

array([[1., 1., 1., 0.],
       [1., 1., 0., 1.]])

Trace and Determinant

In [56]:
x = np.random.randn(2,2)
print(x)

[[-1.90019699  0.20095301]
 [ 1.53978828  0.49151843]]


In [62]:
print(np.linalg.det(x))   # determinant
print(np.trace(x))     # trace

-1.2434069402014105
-1.408678562914297
